FROM docker.io/bitnami/laravel:9

ENV \
  APP_DIR="/app" \
  APP_PORT="80"

COPY . $APP_DIR

WORKDIR $APP_DIR

RUN composer install
RUN php artisan migrate:fresh --seed

CMD php artisan serve --host=0.0.0.0 --port=$APP_PORT
